# Generated by Django 4.0 on 2022-01-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diametr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='len',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
