# Generated by Django 4.0 on 2022-01-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diametr',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='len',
            field=models.IntegerField(blank=True),
        ),
    ]
