# Generated by Django 4.0 on 2022-01-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_diametr_alter_product_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='diametr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='len',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
